import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav data-cy="nav">
          <a data-cy="nav-home" href="/">
            Home
          </a>
          <a data-cy="nav-heat-demand" href="/heat-demand">
            Heat Demand
          </a>
          <a data-cy="nav-breakdown-heat" href="/breakdown/heat">
            Breakdown - Heat
          </a>
          <a data-cy="nav-breakdown-energy" href="/breakdown/energy">
            Breakdown - Energy
          </a>
          <a
            data-cy="nav-half-hourly-gas-boilers"
            href="/half-hourly/gas-boilers"
          >
            Half-hourly - Gas Boilers
          </a>
          <a
            data-cy="nav-half-hourly-resistance-heaters"
            href="/half-hourly/resistance-heaters"
          >
            Half-hourly - Resistance Heaters
          </a>
          <a 
            data-cy="nav-login-sign-in" 
            href="/admin/sign-in"
          >
            Sign In
          </a>
          <a 
            data-cy="nav-login-sign-up" 
            href="/admin/sign-up"
          >
            Sign Up
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
