export const AnnualHeatDemandLSOAHeaders: RegExp[] = [
  /^LSOA\d{2}CD$/,
  /^Area \(km2\)$/,
  /^Average heat demand after energy efficiency measures for detached biomass boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for detached gas boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for detached oil boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for detached resistance heating \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for flat biomass boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for flat gas boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for flat oil boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for flat resistance heating \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for semi-detached biomass boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for semi-detached gas boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for semi-detached oil boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for semi-detached resistance heating \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for terraced biomass boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for terraced gas boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for terraced oil boiler \(kWh\)$/,
  /^Average heat demand after energy efficiency measures for terraced resistance heating \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for detached biomass boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for detached gas boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for detached oil boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for detached resistance heating \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for flat biomass boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for flat gas boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for flat oil boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for flat resistance heating \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for semi-detached biomass boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for semi-detached gas boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for semi-detached oil boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for semi-detached resistance heating \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for terraced biomass boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for terraced gas boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for terraced oil boiler \(kWh\)$/,
  /^Average heat demand before energy efficiency measures for terraced resistance heating \(kWh\)$/,
  /^Local Authority \(\d{4}\)$/,
  /^Local Authority \(\d{4}\)$/,
  /^Number of detached biomass boiler in \d{4}$/,
  /^Number of detached gas boiler in \d{4}$/,
  /^Number of detached oil boiler in \d{4}$/,
  /^Number of detached resistance heating in \d{4}$/,
  /^Number of flat biomass boiler in \d{4}$/,
  /^Number of flat gas boiler in \d{4}$/,
  /^Number of flat oil boiler in \d{4}$/,
  /^Number of flat resistance heating in \d{4}$/,
  /^Number of semi-detached biomass boiler in \d{4}$/,
  /^Number of semi-detached gas boiler in \d{4}$/,
  /^Number of semi-detached oil boiler in \d{4}$/,
  /^Number of semi-detached resistance heating in \d{4}$/,
  /^Number of terraced biomass boiler in \d{4}$/,
  /^Number of terraced gas boiler in \d{4}$/,
  /^Number of terraced oil boiler in \d{4}$/,
  /^Number of terraced resistance heating in \d{4}$/,
  /^Road length \(m\)$/,
  /^Rurality$/,
  /^Total heat demand after energy efficiency measures \d{4} \(kWh\)$/,
  /^Total heat demand before energy efficiency measures \d{4} \(kWh\)$/
];

export const EnergyEfficiencyImprovementsCostsLAHeaders: RegExp[] = [
  /^Local Authority \(\d{4}\)$/,
  /^Average energy efficiency improvements costs of detached gas boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of detached oil boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of detached resistance heating \(GBP\)$/,
  /^Average energy efficiency improvements costs of detached biomass boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of flat gas boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of flat oil boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of flat resistance heating \(GBP\)$/,
  /^Average energy efficiency improvements costs of flat biomass boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of semi-detached gas boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of semi-detached oil boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of semi-detached resistance heating \(GBP\)$/,
  /^Average energy efficiency improvements costs of semi-detached biomass boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of terraced gas boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of terraced oil boiler \(GBP\)$/,
  /^Average energy efficiency improvements costs of terraced resistance heating \(GBP\)$/,
  /^Average energy efficiency improvements costs of terraced biomass boiler \(GBP\)$/,
  /^Number of detached gas boiler in \d{4}$/,
  /^Number of detached resistance heating in \d{4}$/,
  /^Number of detached oil boiler in \d{4}$/,
  /^Number of detached biomass boiler in \d{4}$/,
  /^Number of semi-detached gas boiler in \d{4}$/,
  /^Number of semi-detached resistance heating in \d{4}$/,
  /^Number of semi-detached oil boiler in \d{4}$/,
  /^Number of semi-detached biomass boiler in \d{4}$/,
  /^Number of terraced gas boiler in \d{4}$/,
  /^Number of terraced resistance heating in \d{4}$/,
  /^Number of terraced oil boiler in \d{4}$/,
  /^Number of terraced biomass boiler in \d{4}$/,
  /^Number of flat gas boiler in \d{4}$/,
  /^Number of flat resistance heating in \d{4}$/,
  /^Number of flat oil boiler in \d{4}$/,
  /^Number of flat biomass boiler in \d{4}$/,
  /^Total energy efficiency improvements costs \(GBP\)$/
];

export const HalfHourlyProfilesOfHeatingTechnologiesHeaders: RegExp[] = [
  /^index$/,
  /^Normalised_ASHP_heat$/,
  /^Normalised_ASHP_elec$/,
  /^Normalised_GSHP_heat$/,
  /^Normalised_GSHP_elec$/,
  /^Normalised_Resistance_heater_heat$/,
  /^Normalised_Resistance_heater_elec$/,
  /^Normalised_Gas_boiler_heat$/,
  /^Normalised_Gas_boiler_gas$/,
  /^UK_daily_average_OAT_\[degrees_C\]$/
];
